// <auto-generated />
using System;
using GardenKeeper.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GardenKeeper.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260228081317_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("GardenKeeper.Domain.Entities.GardenBed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LengthFeet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WidthFeet")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GardenBeds");
                });

            modelBuilder.Entity("GardenKeeper.Domain.Entities.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntryType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpectedHarvestDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GardenBedId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GardenBedId");

                    b.HasIndex("PlantId");

                    b.HasIndex("UserId");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("GardenKeeper.Domain.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanionPlants")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CropRotationNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysToMaturity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HardinessZones")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SpacingInches")
                        .HasColumnType("REAL");

                    b.Property<int>("SunRequirement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypicalStartMethod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WaterRequirement")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommonName = "Tomato",
                            CompanionPlants = "Basil, Parsley, Carrot, Marigold",
                            CropRotationNotes = "Rotate out of nightshade family beds annually. Avoid planting after pepper or eggplant.",
                            DataSource = "USDA, OpenFarm",
                            DaysToMaturity = 75,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Kansas staple; start seeds indoors 6-8 weeks before last frost (mid-April).",
                            PlantType = 0,
                            ScientificName = "Solanum lycopersicum",
                            SpacingInches = 24.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 2,
                            CommonName = "Bell Pepper",
                            CompanionPlants = "Tomato, Basil, Carrot",
                            CropRotationNotes = "Nightshade family; rotate with brassicas or legumes.",
                            DataSource = "USDA, OpenFarm",
                            DaysToMaturity = 70,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Needs warm soil; transplant after danger of frost has passed.",
                            PlantType = 0,
                            ScientificName = "Capsicum annuum",
                            SpacingInches = 18.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 3,
                            CommonName = "Cucumber",
                            CompanionPlants = "Beans, Dill, Sunflower",
                            CropRotationNotes = "Cucurbit family; rotate annually to prevent cucumber beetles.",
                            DataSource = "USDA, OpenFarm",
                            DaysToMaturity = 55,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 0,
                            ScientificName = "Cucumis sativus",
                            SpacingInches = 12.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 2
                        },
                        new
                        {
                            Id = 4,
                            CommonName = "Zucchini",
                            CompanionPlants = "Corn, Beans, Nasturtium",
                            CropRotationNotes = "Cucurbit family; rotate with nightshades or brassicas.",
                            DataSource = "USDA",
                            DaysToMaturity = 50,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 0,
                            ScientificName = "Cucurbita pepo",
                            SpacingInches = 36.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 5,
                            CommonName = "Green Bean",
                            CompanionPlants = "Corn, Squash, Carrot, Cucumber",
                            CropRotationNotes = "Legume; fixes nitrogen — plant before heavy feeders like corn.",
                            DataSource = "USDA, OpenFarm",
                            DaysToMaturity = 55,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 0,
                            ScientificName = "Phaseolus vulgaris",
                            SpacingInches = 6.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 6,
                            CommonName = "Sweet Corn",
                            CompanionPlants = "Beans, Squash, Sunflower",
                            CropRotationNotes = "Heavy feeder; rotate with legumes to replenish nitrogen.",
                            DataSource = "USDA",
                            DaysToMaturity = 80,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 0,
                            ScientificName = "Zea mays",
                            SpacingInches = 12.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 2
                        },
                        new
                        {
                            Id = 7,
                            CommonName = "Lettuce",
                            CompanionPlants = "Carrot, Radish, Chives, Dill",
                            CropRotationNotes = "Light feeder; good following heavy feeders.",
                            DataSource = "USDA, OpenFarm",
                            DaysToMaturity = 45,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Best as a spring or fall crop in Kansas; bolts in summer heat.",
                            PlantType = 0,
                            ScientificName = "Lactuca sativa",
                            SpacingInches = 8.0,
                            SunRequirement = 1,
                            TypicalStartMethod = 0,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 8,
                            CommonName = "Spinach",
                            CompanionPlants = "Strawberry, Peas, Brassicas",
                            CropRotationNotes = "Good following root crops; avoid planting with chard.",
                            DataSource = "USDA",
                            DaysToMaturity = 40,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 0,
                            ScientificName = "Spinacia oleracea",
                            SpacingInches = 6.0,
                            SunRequirement = 1,
                            TypicalStartMethod = 0,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 9,
                            CommonName = "Carrot",
                            CompanionPlants = "Tomato, Lettuce, Chives, Rosemary",
                            CropRotationNotes = "Root crop; rotate with leaf or fruit crops.",
                            DataSource = "USDA, OpenFarm",
                            DaysToMaturity = 70,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 0,
                            ScientificName = "Daucus carota subsp. sativus",
                            SpacingInches = 3.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 10,
                            CommonName = "Radish",
                            CompanionPlants = "Lettuce, Spinach, Cucumber, Peas",
                            CropRotationNotes = "Brassica family; rotate annually.",
                            DataSource = "USDA",
                            DaysToMaturity = 25,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 0,
                            ScientificName = "Raphanus sativus",
                            SpacingInches = 2.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 11,
                            CommonName = "Beet",
                            CompanionPlants = "Onion, Lettuce, Cabbage",
                            CropRotationNotes = "Avoid planting near spinach or chard; rotate with nightshades.",
                            DataSource = "USDA",
                            DaysToMaturity = 60,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 0,
                            ScientificName = "Beta vulgaris",
                            SpacingInches = 4.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 12,
                            CommonName = "Kale",
                            CompanionPlants = "Beet, Celery, Onion, Herbs",
                            CropRotationNotes = "Brassica family; rotate annually to prevent clubroot.",
                            DataSource = "USDA, OpenFarm",
                            DaysToMaturity = 60,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Cold-hardy; flavor improves after frost.",
                            PlantType = 0,
                            ScientificName = "Brassica oleracea var. sabellica",
                            SpacingInches = 18.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 13,
                            CommonName = "Broccoli",
                            CompanionPlants = "Onion, Celery, Beet, Chamomile",
                            CropRotationNotes = "Brassica; do not follow other brassicas. Plant after legumes.",
                            DataSource = "USDA",
                            DaysToMaturity = 65,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 0,
                            ScientificName = "Brassica oleracea var. italica",
                            SpacingInches = 18.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 14,
                            CommonName = "Cabbage",
                            CompanionPlants = "Dill, Celery, Onion, Potato",
                            CropRotationNotes = "Brassica; rotate with nightshades or cucurbits.",
                            DataSource = "USDA",
                            DaysToMaturity = 70,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 0,
                            ScientificName = "Brassica oleracea var. capitata",
                            SpacingInches = 18.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 15,
                            CommonName = "Onion",
                            CompanionPlants = "Carrot, Beet, Lettuce, Chamomile",
                            CropRotationNotes = "Allium; rotate with brassicas or legumes.",
                            DataSource = "USDA, OpenFarm",
                            DaysToMaturity = 100,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 0,
                            ScientificName = "Allium cepa",
                            SpacingInches = 4.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 16,
                            CommonName = "Garlic",
                            CompanionPlants = "Tomato, Pepper, Beet, Rose",
                            CropRotationNotes = "Allium; plant in fall, harvest summer. Rotate with brassicas.",
                            DataSource = "USDA",
                            DaysToMaturity = 240,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Plant cloves in October; harvest late June in Kansas.",
                            PlantType = 0,
                            ScientificName = "Allium sativum",
                            SpacingInches = 6.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 17,
                            CommonName = "Pumpkin",
                            CompanionPlants = "Corn, Beans, Marigold",
                            CropRotationNotes = "Cucurbit; rotate annually.",
                            DataSource = "USDA",
                            DaysToMaturity = 100,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 0,
                            ScientificName = "Cucurbita pepo",
                            SpacingInches = 60.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 18,
                            CommonName = "Butternut Squash",
                            CompanionPlants = "Corn, Beans, Nasturtium",
                            CropRotationNotes = "Cucurbit family; 3-year rotation recommended.",
                            DataSource = "USDA, OpenFarm",
                            DaysToMaturity = 110,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 0,
                            ScientificName = "Cucurbita moschata",
                            SpacingInches = 48.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 19,
                            CommonName = "Sweet Potato",
                            CompanionPlants = "Beans, Thyme, Oregano",
                            CropRotationNotes = "Avoid planting in same location as other morning-glories or tomatoes.",
                            DataSource = "USDA",
                            DaysToMaturity = 100,
                            HardinessZones = "6a,6b,7a",
                            Notes = "Thrives in southern Kansas (zone 6b-7a); needs 100+ frost-free days.",
                            PlantType = 0,
                            ScientificName = "Ipomoea batatas",
                            SpacingInches = 12.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 20,
                            CommonName = "Potato",
                            CompanionPlants = "Beans, Corn, Horseradish",
                            CropRotationNotes = "Nightshade; rotate with brassicas or legumes. Do not follow tomato.",
                            DataSource = "USDA",
                            DaysToMaturity = 80,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 0,
                            ScientificName = "Solanum tuberosum",
                            SpacingInches = 12.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 21,
                            CommonName = "Eggplant",
                            CompanionPlants = "Tomato, Pepper, Basil",
                            CropRotationNotes = "Nightshade; rotate with legumes or brassicas.",
                            DataSource = "USDA",
                            DaysToMaturity = 80,
                            HardinessZones = "6a,6b,7a",
                            PlantType = 0,
                            ScientificName = "Solanum melongena",
                            SpacingInches = 24.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 22,
                            CommonName = "Swiss Chard",
                            CompanionPlants = "Beans, Cabbage, Onion",
                            CropRotationNotes = "Related to beet; avoid following beet or spinach.",
                            DataSource = "USDA",
                            DaysToMaturity = 60,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 0,
                            ScientificName = "Beta vulgaris subsp. vulgaris",
                            SpacingInches = 12.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 23,
                            CommonName = "Strawberry",
                            CompanionPlants = "Spinach, Lettuce, Thyme, Borage",
                            CropRotationNotes = "Perennial; replace bed every 3-4 years. Avoid planting with cabbage.",
                            DataSource = "USDA, OpenFarm",
                            DaysToMaturity = 30,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "June-bearing varieties most common in Kansas.",
                            PlantType = 1,
                            ScientificName = "Fragaria × ananassa",
                            SpacingInches = 12.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 24,
                            CommonName = "Watermelon",
                            CompanionPlants = "Corn, Sunflower, Nasturtium",
                            CropRotationNotes = "Cucurbit; 3-year rotation. Kansas summers ideal.",
                            DataSource = "USDA",
                            DaysToMaturity = 85,
                            HardinessZones = "6a,6b,7a",
                            PlantType = 1,
                            ScientificName = "Citrullus lanatus",
                            SpacingInches = 72.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 2
                        },
                        new
                        {
                            Id = 25,
                            CommonName = "Cantaloupe",
                            CompanionPlants = "Corn, Sunflower, Radish",
                            CropRotationNotes = "Cucurbit family; rotate with nightshades or brassicas.",
                            DataSource = "USDA",
                            DaysToMaturity = 80,
                            HardinessZones = "6a,6b,7a",
                            PlantType = 1,
                            ScientificName = "Cucumis melo var. cantalupensis",
                            SpacingInches = 48.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 26,
                            CommonName = "Blackberry",
                            CompanionPlants = "Comfrey, Tansy, Marigold",
                            CropRotationNotes = "Perennial bramble; permanent planting. Keep away from raspberries.",
                            DataSource = "USDA",
                            DaysToMaturity = 365,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Native-adjacent thorny varieties very well adapted to Kansas.",
                            PlantType = 1,
                            ScientificName = "Rubus allegheniensis",
                            SpacingInches = 36.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 27,
                            CommonName = "Basil",
                            CompanionPlants = "Tomato, Pepper, Oregano",
                            CropRotationNotes = "Annual; rotate freely.",
                            DataSource = "OpenFarm",
                            DaysToMaturity = 30,
                            HardinessZones = "6a,6b,7a",
                            Notes = "Repels aphids and whiteflies; excellent tomato companion.",
                            PlantType = 3,
                            ScientificName = "Ocimum basilicum",
                            SpacingInches = 12.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 28,
                            CommonName = "Cilantro",
                            CompanionPlants = "Spinach, Lettuce, Dill, Carrot",
                            CropRotationNotes = "Annual herb; minimal rotation concern.",
                            DataSource = "OpenFarm",
                            DaysToMaturity = 45,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Bolts quickly in Kansas summer; grow in spring/fall.",
                            PlantType = 3,
                            ScientificName = "Coriandrum sativum",
                            SpacingInches = 6.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 29,
                            CommonName = "Parsley",
                            CompanionPlants = "Tomato, Asparagus, Rose",
                            CropRotationNotes = "Biennial; carrot family. Rotate with other families.",
                            DataSource = "USDA",
                            DaysToMaturity = 70,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 3,
                            ScientificName = "Petroselinum crispum",
                            SpacingInches = 8.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 30,
                            CommonName = "Dill",
                            CompanionPlants = "Cucumber, Lettuce, Onion, Brassicas",
                            CropRotationNotes = "Carrot family annual; keep away from mature fennel.",
                            DataSource = "OpenFarm",
                            DaysToMaturity = 40,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 3,
                            ScientificName = "Anethum graveolens",
                            SpacingInches = 12.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 31,
                            CommonName = "Chives",
                            CompanionPlants = "Carrot, Tomato, Apple, Rose",
                            CropRotationNotes = "Perennial allium; permanent planting in herb bed.",
                            DataSource = "USDA",
                            DaysToMaturity = 60,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 3,
                            ScientificName = "Allium schoenoprasum",
                            SpacingInches = 6.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 32,
                            CommonName = "Mint",
                            CompanionPlants = "Tomato, Brassicas, Peas",
                            CropRotationNotes = "Perennial; contains aggressively — consider containers.",
                            DataSource = "OpenFarm",
                            DaysToMaturity = 90,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Very invasive; grow in containers or with root barrier.",
                            PlantType = 3,
                            ScientificName = "Mentha spicata",
                            SpacingInches = 24.0,
                            SunRequirement = 1,
                            TypicalStartMethod = 2,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 33,
                            CommonName = "Oregano",
                            CompanionPlants = "Pepper, Tomato, Squash",
                            CropRotationNotes = "Perennial herb; permanent bed planting.",
                            DataSource = "OpenFarm",
                            DaysToMaturity = 80,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 3,
                            ScientificName = "Origanum vulgare",
                            SpacingInches = 12.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 34,
                            CommonName = "Thyme",
                            CompanionPlants = "Tomato, Eggplant, Cabbage, Strawberry",
                            CropRotationNotes = "Perennial; low maintenance. Good border plant.",
                            DataSource = "USDA, OpenFarm",
                            DaysToMaturity = 90,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 3,
                            ScientificName = "Thymus vulgaris",
                            SpacingInches = 12.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 35,
                            CommonName = "Sage",
                            CompanionPlants = "Tomato, Cabbage, Carrot, Strawberry",
                            CropRotationNotes = "Perennial shrubby herb; replace every 3-4 years.",
                            DataSource = "USDA",
                            DaysToMaturity = 75,
                            HardinessZones = "5b,6a,6b,7a",
                            PlantType = 3,
                            ScientificName = "Salvia officinalis",
                            SpacingInches = 24.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 36,
                            CommonName = "Lavender",
                            CompanionPlants = "Rose, Sage, Thyme, Brassicas",
                            CropRotationNotes = "Perennial; permanent planting. Excellent pollinator attractor.",
                            DataSource = "USDA, OpenFarm",
                            DaysToMaturity = 90,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Excellent deer-resistant pollinator plant for Kansas.",
                            PlantType = 3,
                            ScientificName = "Lavandula angustifolia",
                            SpacingInches = 24.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 37,
                            CommonName = "Purple Coneflower",
                            CompanionPlants = "Black-eyed Susan, Wild Bergamot, Blazing Star",
                            CropRotationNotes = "Perennial native; leave seed heads for birds over winter.",
                            DataSource = "USDA",
                            DaysToMaturity = 365,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Kansas native; drought-tolerant; blooms June-October.",
                            PlantType = 4,
                            ScientificName = "Echinacea purpurea",
                            SpacingInches = 18.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 38,
                            CommonName = "Black-eyed Susan",
                            CompanionPlants = "Coneflower, Blazing Star, Wild Bergamot",
                            CropRotationNotes = "Biennial/perennial native; self-seeds readily.",
                            DataSource = "USDA",
                            DaysToMaturity = 365,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Official wildflower of Maryland; widely naturalized in Kansas.",
                            PlantType = 4,
                            ScientificName = "Rudbeckia hirta",
                            SpacingInches = 18.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 39,
                            CommonName = "Wild Bergamot",
                            CompanionPlants = "Coneflower, Black-eyed Susan, Prairie Clover",
                            CropRotationNotes = "Perennial native; spreads by rhizomes. Divide every 3 years.",
                            DataSource = "USDA",
                            DaysToMaturity = 365,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Excellent native bee and butterfly plant; aromatic foliage.",
                            PlantType = 4,
                            ScientificName = "Monarda fistulosa",
                            SpacingInches = 24.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 40,
                            CommonName = "Prairie Blazing Star",
                            CompanionPlants = "Coneflower, Black-eyed Susan, Wild Bergamot",
                            CropRotationNotes = "Perennial corm; permanent planting.",
                            DataSource = "USDA",
                            DaysToMaturity = 365,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Kansas native; monarch butterfly magnet; blooms August-September.",
                            PlantType = 4,
                            ScientificName = "Liatris pycnostachya",
                            SpacingInches = 18.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 41,
                            CommonName = "Butterfly Weed",
                            CompanionPlants = "Prairie Blazing Star, Coneflower, Goldenrod",
                            CropRotationNotes = "Deep tap root; do not transplant once established.",
                            DataSource = "USDA",
                            DaysToMaturity = 365,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Essential monarch butterfly host plant; native milkweed.",
                            PlantType = 4,
                            ScientificName = "Asclepias tuberosa",
                            SpacingInches = 18.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 42,
                            CommonName = "Plains Sunflower",
                            CompanionPlants = "Corn, Cucumber, Tomato",
                            CropRotationNotes = "Annual; excellent insectary plant and bird food source.",
                            DataSource = "USDA",
                            DaysToMaturity = 80,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "State flower of Kansas. Direct-sow after last frost.",
                            PlantType = 4,
                            ScientificName = "Helianthus annuus",
                            SpacingInches = 24.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 43,
                            CommonName = "Blue Wild Indigo",
                            CompanionPlants = "Wild Bergamot, Prairie Clover, Coneflower",
                            CropRotationNotes = "Long-lived perennial; fixes nitrogen. Do not move once established.",
                            DataSource = "USDA",
                            DaysToMaturity = 365,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Deep-rooted prairie legume; slow to establish but very long-lived.",
                            PlantType = 4,
                            ScientificName = "Baptisia australis",
                            SpacingInches = 36.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 44,
                            CommonName = "Compass Plant",
                            CompanionPlants = "Prairie Blazing Star, Wild Bergamot, Compass Plant",
                            CropRotationNotes = "Perennial; tap root can reach 15 feet deep. Do not disturb.",
                            DataSource = "USDA",
                            DaysToMaturity = 365,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Iconic tallgrass prairie species; leaves orient north-south.",
                            PlantType = 4,
                            ScientificName = "Silphium laciniatum",
                            SpacingInches = 36.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 45,
                            CommonName = "Ironweed",
                            CompanionPlants = "Goldenrod, Wild Bergamot, Ironweed",
                            CropRotationNotes = "Perennial native; spreading clumps, divide every 4 years.",
                            DataSource = "USDA",
                            DaysToMaturity = 365,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Brilliant purple blooms in late summer; attracts many butterfly species.",
                            PlantType = 4,
                            ScientificName = "Vernonia fasciculata",
                            SpacingInches = 24.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 1
                        },
                        new
                        {
                            Id = 46,
                            CommonName = "Wild Columbine",
                            CompanionPlants = "Wild Ginger, Wild Bergamot, Ferns",
                            CropRotationNotes = "Perennial; self-seeds. Good woodland edge plant.",
                            DataSource = "USDA",
                            DaysToMaturity = 365,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Native to eastern Kansas; hummingbird favorite; early spring bloomer.",
                            PlantType = 4,
                            ScientificName = "Aquilegia canadensis",
                            SpacingInches = 12.0,
                            SunRequirement = 1,
                            TypicalStartMethod = 0,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 47,
                            CommonName = "Purple Prairie Clover",
                            CompanionPlants = "Prairie Blazing Star, Wild Bergamot, Coneflower",
                            CropRotationNotes = "Perennial legume; fixes nitrogen. Permanent planting.",
                            DataSource = "USDA",
                            DaysToMaturity = 365,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Essential native bee plant; extremely drought-tolerant.",
                            PlantType = 4,
                            ScientificName = "Dalea purpurea",
                            SpacingInches = 18.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 0,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 48,
                            CommonName = "Prairie Phlox",
                            CompanionPlants = "Wild Columbine, Wild Bergamot, Coneflower",
                            CropRotationNotes = "Perennial; divide every 3 years to keep vigorous.",
                            DataSource = "USDA",
                            DaysToMaturity = 365,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Fragrant spring bloomer; native to Kansas prairies.",
                            PlantType = 4,
                            ScientificName = "Phlox pilosa",
                            SpacingInches = 12.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 49,
                            CommonName = "Wild Petunia",
                            CompanionPlants = "Wild Columbine, Prairie Phlox, Coneflower",
                            CropRotationNotes = "Perennial native; self-seeds freely.",
                            DataSource = "USDA",
                            DaysToMaturity = 365,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Low-growing native great for garden edges and dry spots.",
                            PlantType = 4,
                            ScientificName = "Ruellia humilis",
                            SpacingInches = 18.0,
                            SunRequirement = 1,
                            TypicalStartMethod = 0,
                            WaterRequirement = 0
                        },
                        new
                        {
                            Id = 50,
                            CommonName = "Prairie Dropseed",
                            CompanionPlants = "Purple Prairie Clover, Coneflower, Wild Bergamot",
                            CropRotationNotes = "Perennial native grass; permanent planting.",
                            DataSource = "USDA",
                            DaysToMaturity = 365,
                            HardinessZones = "5b,6a,6b,7a",
                            Notes = "Fragrant native bunchgrass; excellent four-season interest.",
                            PlantType = 4,
                            ScientificName = "Sporobolus heterolepis",
                            SpacingInches = 24.0,
                            SunRequirement = 0,
                            TypicalStartMethod = 2,
                            WaterRequirement = 0
                        });
                });

            modelBuilder.Entity("GardenKeeper.Domain.Entities.PlantPlacement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GardenBedId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GridX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GridY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GardenBedId");

                    b.HasIndex("PlantId");

                    b.ToTable("PlantPlacements");
                });

            modelBuilder.Entity("GardenKeeper.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HardinessZone")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GardenKeeper.Domain.Entities.LogEntry", b =>
                {
                    b.HasOne("GardenKeeper.Domain.Entities.GardenBed", "GardenBed")
                        .WithMany("LogEntries")
                        .HasForeignKey("GardenBedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GardenKeeper.Domain.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GardenBed");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GardenKeeper.Domain.Entities.PlantPlacement", b =>
                {
                    b.HasOne("GardenKeeper.Domain.Entities.GardenBed", "GardenBed")
                        .WithMany("PlantPlacements")
                        .HasForeignKey("GardenBedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GardenKeeper.Domain.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GardenBed");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GardenKeeper.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GardenKeeper.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GardenKeeper.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GardenKeeper.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GardenKeeper.Domain.Entities.GardenBed", b =>
                {
                    b.Navigation("LogEntries");

                    b.Navigation("PlantPlacements");
                });
#pragma warning restore 612, 618
        }
    }
}
